---
title: "Homework1HochRobinson"
format: html
editor: visual
languages:
  - name: bash
    command: bash

---

## 1

shell is any program that uses command-line as an interface. Bash is a specific type of shell.


My home directory is c/Users/ellah/


I found this by typing cd into my bash terminal after navigating to a different folder

To navigate to my notes I would type cd HomeworkHochRobinson

I cloned the directory into my home directory so that would get me to the folder with my notes. To get back to my home directory I could type cd or cd ..

There are a lot of folders in my home directory like downloads, documents, photos, applicaitons, and some old git repos.



## 2.

The cd~/../../.. takes me to my home directory, than up three folders. For me, this first takes me to Users, than c: (hard drive), then one level above the hard drive which seems to have several terminals that I have installed and temporary memory.

## 3.

The flag -a for the ls command will list all the files in the directory without ignoring files that start with "."

The flag -l for ls means long listing format. It includes information about the date and size of each file or folder listed.

## 4.

Running stat myfile.txt details the history of the file, like when it was created and where the file is stored.

## 5.

ls -l gives me information about the directory each file is stored in as well as when it was last changed and by who.

## 7.

both touch and writing a new line to the test file updated the timestamp listed with ls -l.



